services:
  database:
    image: mariadb:10.11
    container_name: convite-db
    environment:
      MARIADB_ROOT_PASSWORD: Br@@5up3r
      MARIADB_DATABASE: convite
      MARIADB_USER: bradmin
      MARIADB_PASSWORD: Br@@5up3r
      MARIADB_PORT: 3306
    ports:
      - '3306:3306'
    volumes:
      - ./data/database:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  # webapp:
  #   container_name: 'brtools-webapp__dev'
  #   image: oven/bun:1.2.2-slim
  #   depends_on:
  #     - api
  #   command: sh -c "bun install && bun --bun dev"
  #   ports:
  #     - '3000:3000'
