version: '3.8'

services:
  database:
    image: mariadb:10.11
    container_name: convite-db
    environment:
      MARIADB_ROOT_PASSWORD: Br@@5up3r
      MARIADB_DATABASE: convite
      MARIADB_USER: bradmin
      MARIADB_PASSWORD: Br@@5up3r
    volumes:
      - ./data/database:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  web:
    container_name: convite-web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://bradmin:Br@@5up3r@database:3306/convite
    command: sh -c "pnpm dlx prisma migrate deploy && pnpm start"
    ports:
      - '3333:3000'
    depends_on:
      - database
